name: hmat_mi
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dio: ^5.9.1
  dotenv: ^4.2.0
  encrypt: ^5.0.3
  google_generative_ai: ^0.4.7
  json_annotation: ^4.10.0
  logger: ^2.6.2
  supabase: ^2.10.2
  teledart: ^0.6.1

dev_dependencies:
  build_runner: ^2.3.3
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
